### ISSUE TITLE
文字消息有些会被截断

### ISSUE THREAD

**Issue by keepJion** [samuelandkevin/YHChat#1]
![image](https://cloud.githubusercontent.com/assets/14191891/25804039/5ffbd2e2-342c-11e7-9e22-e342ba098b7d.png)
hi, 文字会被截断!

**Comment by samuelandkevin** [comment]
谢谢您的反馈，已经修复bug。请更新一下。

**Comment by keepJion** [comment]
主要是什么引起的呢?  我之前也遇到文字会被截断    计算不是很准确

**Comment by samuelandkevin** [comment]
一般是preferredMaxLayoutWidth没有设置正确。上次那bug其实高度是没有计算错误的，是渲染出错了。因为我的富文本处理是采用YYLabel，YYLabel有一个属性ignoreCommonProperties，默认是NO.当时没有设置为YES，在6plus设置中会出现文字截断。
